### ISSUE TITLE
Kinetic augment usage directions in turtles

### ISSUE THREAD

**Issue by DukeAbigor** [SwitchCraftCC/Plethora-Fabric#20]
KineticTurtleUpgrade.useTool should be removed and useUp/useDown/swingUp/swingDown should be implemented

**Comment by Allymonies** [comment]
useTool causes this unexpected behavior where a turtle will attempt to destroy itself, and makes mining in general not act as expected.
![image](https://user-images.githubusercontent.com/7727003/215297964-96e5edc7-6149-43f1-9143-6cc1eec275d0.png)

**Comment by Lemmmy** [comment]
To clarify what is actually going on here, with the help of TheJebForge's testing and explanations:

The Kinetic Augment when equipped as a Turtle upgrade will act as a tool. It provides behavior for `turtle.dig()` and `turtle.attack()`. For the Kinetic Augment, these behaviors delegate to kinetic.swing(). 

Turtles will try to use the left tool first, and then the right tool. In the event that the left tool does not do anything, the right tool will be attempted. That's what's happening in Allymonies' screenshot: turtle.digUp() is called, the Diamond Pickaxe cannot be used (no block there), and the Kinetic Augment gets tried instead.

The problem here is that the fake player's position for the raycast in KineticTurtleUpgrade is slightly wrong. I was originally going to remove the useTool implementation but after understanding the behavior a bit better I am going to try and fix it instead. I will still add a "direction" argument to kinetic.use/kinetic.swing for turtles, or separate digUp/etc. methods, not sure yet

**Comment by Lemmmy** [comment]
6_4 suggested that this may have been fixed, possibly by 4077b291f6e88bf68e1f893cf03f3b18a201c7d9 ? Would need to test the repro between 1.4.3 and 1.4.4 to confirm

**Comment by Kan18** [comment]
I just checked and this was not fixed; turtles can still mine themselves. I was probably reproducing it incorrectly in some way last time (maybe forgetting to use digUp?)
