### ISSUE TITLE
Incorrect yaw in Kinetic Augment launch during Elytra flight

### ISSUE THREAD

**Issue by hugeblank** [SwitchCraftCC/Plethora-Fabric#30]
While flying with an elytra, especially while looking at angles 10+ degrees offset from a cardinal direction, it's apparent that the kinetic augment launch method is not correctly calculating the motion. When looking at (-100 0), it's very clear that the augment is pushing me more towards (-180 0) while my elytra is trying to compensate for it by actually using my look direction, the sum of the vectors landing at something like (-135 0). This may affect pitch too but I'm having a harder time noticing/testing it. When not in elytra flight everything behaves as intended.

**Comment by Wojbie** [comment]
Can you show example of code that could reproduce your issue? 
I have been using kinetic to push player in direction of looking and it seems to work correctly in my use?
I do not understand what you are trying to exactly describe here.

**Comment by hugeblank** [comment]
https://p.sc3.io/d6xK2WkcpR This is the code that I'm using. I should have attached it in the report, forgot to. I thought it might have been the fact that I was only launching when the player was sneaking and elytra flying, but when changing the code to launch only when elytra flying it still happened.

**Comment by hugeblank** [comment]
https://www.youtube.com/watch?v=uh8jL_JXGj8 I decided to break out OBS.

**Comment by Kan18** [comment]
I did some testing and cannot reproduce this anymore. It might have been fixed by the 1.19.4 update. @hugeblank ?

**Comment by hugeblank** [comment]
I haven't been able to test recently but it has definitely was still an issue after the 1.19.4 update.
